# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmPrincipal.ui'
#
# Created by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

from frmFormato import frm_formato
from resources.jsonFormato import json_formato
from resources.rest import *

jsonFormato = json_formato()
recurso = resources()
base = "http://localhost:8080/clinicaTest-war/ws/"
idIngreso = ()

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # try:
        self.frmIngresoNuevo = None
        self.editar_ingreso = None
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(913, 712)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(7)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.lblListaIngreso = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblListaIngreso.sizePolicy().hasHeightForWidth())
        self.lblListaIngreso.setSizePolicy(sizePolicy)
        self.lblListaIngreso.setSizeIncrement(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblListaIngreso.setFont(font)
        self.lblListaIngreso.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaIngreso.setObjectName(_fromUtf8("lblListaIngreso"))
        self.verticalLayout_10.addWidget(self.lblListaIngreso)
        self.tblIngreso = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblIngreso.sizePolicy().hasHeightForWidth())
        self.tblIngreso.setSizePolicy(sizePolicy)
        self.tblIngreso.setMaximumSize(QtCore.QSize(803, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tblIngreso.setFont(font)
        self.tblIngreso.setFrameShape(QtGui.QFrame.Box)
        self.tblIngreso.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblIngreso.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblIngreso.setGridStyle(QtCore.Qt.SolidLine)
        self.tblIngreso.setCornerButtonEnabled(False)
        self.tblIngreso.setRowCount(0)
        self.tblIngreso.setColumnCount(6)
        self.tblIngreso.setObjectName(_fromUtf8("tblIngreso"))
        item = QtGui.QTableWidgetItem()
        self.tblIngreso.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngreso.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngreso.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngreso.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngreso.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngreso.setHorizontalHeaderItem(5, item)
        self.tblIngreso.horizontalHeader().setVisible(True)
        self.tblIngreso.horizontalHeader().setDefaultSectionSize(130)
        self.tblIngreso.horizontalHeader().setHighlightSections(True)
        self.tblIngreso.horizontalHeader().setMinimumSectionSize(50)
        self.tblIngreso.verticalHeader().setVisible(False)
        self.tblIngreso.verticalHeader().setHighlightSections(False)
        self.verticalLayout_10.addWidget(self.tblIngreso)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem = QtGui.QSpacerItem(20, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem)
        self.btnNuevoIngreso = QtGui.QPushButton(self.centralwidget)
        self.btnNuevoIngreso.setDefault(False)
        self.btnNuevoIngreso.setFlat(False)
        self.btnNuevoIngreso.setObjectName(_fromUtf8("btnNuevoIngreso"))
        self.verticalLayout_7.addWidget(self.btnNuevoIngreso)
        self.btnEditarIngreso = QtGui.QPushButton(self.centralwidget)
        self.btnEditarIngreso.setObjectName(_fromUtf8("btnEditarIngreso"))
        self.verticalLayout_7.addWidget(self.btnEditarIngreso)
        self.btnEliminarIngreso = QtGui.QPushButton(self.centralwidget)
        self.btnEliminarIngreso.setObjectName(_fromUtf8("btnEliminarIngreso"))
        self.verticalLayout_7.addWidget(self.btnEliminarIngreso)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblPaciente = QtGui.QLabel(self.centralwidget)
        self.lblPaciente.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblPaciente.setFont(font)
        self.lblPaciente.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblPaciente.setObjectName(_fromUtf8("lblPaciente"))
        self.horizontalLayout_5.addWidget(self.lblPaciente)
        self.txtPaciente = QtGui.QTextEdit(self.centralwidget)
        self.txtPaciente.setEnabled(True)
        self.txtPaciente.setMaximumSize(QtCore.QSize(335, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtPaciente.setFont(font)
        self.txtPaciente.setFrameShape(QtGui.QFrame.Box)
        self.txtPaciente.setReadOnly(True)
        self.txtPaciente.setObjectName(_fromUtf8("txtPaciente"))
        self.horizontalLayout_5.addWidget(self.txtPaciente)
        spacerItem2 = QtGui.QSpacerItem(350, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblIngreso_2 = QtGui.QLabel(self.centralwidget)
        self.lblIngreso_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblIngreso_2.setFont(font)
        self.lblIngreso_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblIngreso_2.setObjectName(_fromUtf8("lblIngreso_2"))
        self.horizontalLayout.addWidget(self.lblIngreso_2)
        self.txtIngreso = QtGui.QTextEdit(self.centralwidget)
        self.txtIngreso.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtIngreso.setFont(font)
        self.txtIngreso.setFrameShape(QtGui.QFrame.Box)
        self.txtIngreso.setReadOnly(True)
        self.txtIngreso.setOverwriteMode(False)
        self.txtIngreso.setObjectName(_fromUtf8("txtIngreso"))
        self.horizontalLayout.addWidget(self.txtIngreso)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lblFechaIngreso = QtGui.QLabel(self.centralwidget)
        self.lblFechaIngreso.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblFechaIngreso.setFont(font)
        self.lblFechaIngreso.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblFechaIngreso.setObjectName(_fromUtf8("lblFechaIngreso"))
        self.horizontalLayout.addWidget(self.lblFechaIngreso)
        self.txtFechaIngreso = QtGui.QTextEdit(self.centralwidget)
        self.txtFechaIngreso.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtFechaIngreso.setFont(font)
        self.txtFechaIngreso.setFrameShape(QtGui.QFrame.Box)
        self.txtFechaIngreso.setReadOnly(True)
        self.txtFechaIngreso.setObjectName(_fromUtf8("txtFechaIngreso"))
        self.horizontalLayout.addWidget(self.txtFechaIngreso)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblTipoINgreso = QtGui.QLabel(self.centralwidget)
        self.lblTipoINgreso.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblTipoINgreso.setFont(font)
        self.lblTipoINgreso.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblTipoINgreso.setObjectName(_fromUtf8("lblTipoINgreso"))
        self.horizontalLayout_2.addWidget(self.lblTipoINgreso)
        self.txtTipoIngreso = QtGui.QTextEdit(self.centralwidget)
        self.txtTipoIngreso.setMaximumSize(QtCore.QSize(250, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtTipoIngreso.setFont(font)
        self.txtTipoIngreso.setFrameShape(QtGui.QFrame.Box)
        self.txtTipoIngreso.setReadOnly(True)
        self.txtTipoIngreso.setObjectName(_fromUtf8("txtTipoIngreso"))
        self.horizontalLayout_2.addWidget(self.txtTipoIngreso)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.lblFechaEgreso = QtGui.QLabel(self.centralwidget)
        self.lblFechaEgreso.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblFechaEgreso.setFont(font)
        self.lblFechaEgreso.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblFechaEgreso.setObjectName(_fromUtf8("lblFechaEgreso"))
        self.horizontalLayout_2.addWidget(self.lblFechaEgreso)
        self.txtFechaEgreso = QtGui.QTextEdit(self.centralwidget)
        self.txtFechaEgreso.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtFechaEgreso.setFont(font)
        self.txtFechaEgreso.setFrameShape(QtGui.QFrame.Box)
        self.txtFechaEgreso.setReadOnly(True)
        self.txtFechaEgreso.setObjectName(_fromUtf8("txtFechaEgreso"))
        self.horizontalLayout_2.addWidget(self.txtFechaEgreso)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem5 = QtGui.QSpacerItem(90, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtGui.QSpacerItem(400, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.lblListaIngresoDetalle = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblListaIngresoDetalle.sizePolicy().hasHeightForWidth())
        self.lblListaIngresoDetalle.setSizePolicy(sizePolicy)
        self.lblListaIngresoDetalle.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblListaIngresoDetalle.setFont(font)
        self.lblListaIngresoDetalle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblListaIngresoDetalle.setObjectName(_fromUtf8("lblListaIngresoDetalle"))
        self.verticalLayout_11.addWidget(self.lblListaIngresoDetalle)
        self.tblIngresoDetalle = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblIngresoDetalle.sizePolicy().hasHeightForWidth())
        self.tblIngresoDetalle.setSizePolicy(sizePolicy)
        self.tblIngresoDetalle.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tblIngresoDetalle.setFont(font)
        self.tblIngresoDetalle.setFrameShape(QtGui.QFrame.Box)
        self.tblIngresoDetalle.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblIngresoDetalle.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblIngresoDetalle.setCornerButtonEnabled(False)
        self.tblIngresoDetalle.setObjectName(_fromUtf8("tblIngresoDetalle"))
        self.tblIngresoDetalle.setColumnCount(8)
        self.tblIngresoDetalle.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblIngresoDetalle.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngresoDetalle.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngresoDetalle.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngresoDetalle.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngresoDetalle.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngresoDetalle.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngresoDetalle.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tblIngresoDetalle.setHorizontalHeaderItem(7, item)
        self.tblIngresoDetalle.horizontalHeader().setVisible(True)
        self.tblIngresoDetalle.horizontalHeader().setDefaultSectionSize(160)
        self.tblIngresoDetalle.verticalHeader().setVisible(False)
        self.verticalLayout_11.addWidget(self.tblIngresoDetalle)
        spacerItem7 = QtGui.QSpacerItem(40, 5, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_11.addItem(spacerItem7)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.lblIngreso = QtGui.QLabel(self.centralwidget)
        self.lblIngreso.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblIngreso.setFont(font)
        self.lblIngreso.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblIngreso.setObjectName(_fromUtf8("lblIngreso"))
        self.horizontalLayout_11.addWidget(self.lblIngreso)
        self.txtIngresoDetalle = QtGui.QTextEdit(self.centralwidget)
        self.txtIngresoDetalle.setMaximumSize(QtCore.QSize(250, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtIngresoDetalle.setFont(font)
        self.txtIngresoDetalle.setFrameShape(QtGui.QFrame.Box)
        self.txtIngresoDetalle.setReadOnly(True)
        self.txtIngresoDetalle.setObjectName(_fromUtf8("txtIngresoDetalle"))
        self.horizontalLayout_11.addWidget(self.txtIngresoDetalle)
        spacerItem8 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.lblFechaDetalle = QtGui.QLabel(self.centralwidget)
        self.lblFechaDetalle.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblFechaDetalle.setFont(font)
        self.lblFechaDetalle.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblFechaDetalle.setObjectName(_fromUtf8("lblFechaDetalle"))
        self.horizontalLayout_11.addWidget(self.lblFechaDetalle)
        self.txtFechaDetalle = QtGui.QTextEdit(self.centralwidget)
        self.txtFechaDetalle.setMaximumSize(QtCore.QSize(300, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtFechaDetalle.setFont(font)
        self.txtFechaDetalle.setFrameShape(QtGui.QFrame.Box)
        self.txtFechaDetalle.setReadOnly(True)
        self.txtFechaDetalle.setObjectName(_fromUtf8("txtFechaDetalle"))
        self.horizontalLayout_11.addWidget(self.txtFechaDetalle)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lblArea = QtGui.QLabel(self.centralwidget)
        self.lblArea.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblArea.setFont(font)
        self.lblArea.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblArea.setObjectName(_fromUtf8("lblArea"))
        self.horizontalLayout_10.addWidget(self.lblArea)
        self.txtArea = QtGui.QTextEdit(self.centralwidget)
        self.txtArea.setMaximumSize(QtCore.QSize(250, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtArea.setFont(font)
        self.txtArea.setFrameShape(QtGui.QFrame.Box)
        self.txtArea.setReadOnly(True)
        self.txtArea.setObjectName(_fromUtf8("txtArea"))
        self.horizontalLayout_10.addWidget(self.txtArea)
        spacerItem9 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.lblCentro = QtGui.QLabel(self.centralwidget)
        self.lblCentro.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblCentro.setFont(font)
        self.lblCentro.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblCentro.setObjectName(_fromUtf8("lblCentro"))
        self.horizontalLayout_10.addWidget(self.lblCentro)
        self.txtCentro = QtGui.QTextEdit(self.centralwidget)
        self.txtCentro.setMaximumSize(QtCore.QSize(300, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtCentro.setFont(font)
        self.txtCentro.setFrameShape(QtGui.QFrame.Box)
        self.txtCentro.setReadOnly(True)
        self.txtCentro.setObjectName(_fromUtf8("txtCentro"))
        self.horizontalLayout_10.addWidget(self.txtCentro)
        self.verticalLayout_16.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lblDoctor = QtGui.QLabel(self.centralwidget)
        self.lblDoctor.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblDoctor.setFont(font)
        self.lblDoctor.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.lblDoctor.setObjectName(_fromUtf8("lblDoctor"))
        self.horizontalLayout_6.addWidget(self.lblDoctor)
        self.txtPersonal = QtGui.QTextEdit(self.centralwidget)
        self.txtPersonal.setMaximumSize(QtCore.QSize(340, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtPersonal.setFont(font)
        self.txtPersonal.setFrameShape(QtGui.QFrame.Box)
        self.txtPersonal.setReadOnly(True)
        self.txtPersonal.setObjectName(_fromUtf8("txtPersonal"))
        self.horizontalLayout_6.addWidget(self.txtPersonal)
        spacerItem10 = QtGui.QSpacerItem(350, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        self.verticalLayout_11.addLayout(self.verticalLayout_16)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        spacerItem11 = QtGui.QSpacerItem(20, 70, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_15.addItem(spacerItem11)
        self.btnNuevoIngresoDetalle = QtGui.QPushButton(self.centralwidget)
        self.btnNuevoIngresoDetalle.setObjectName(_fromUtf8("btnNuevoIngresoDetalle"))
        self.verticalLayout_15.addWidget(self.btnNuevoIngresoDetalle)
        self.btnEditarIngresoDetalle = QtGui.QPushButton(self.centralwidget)
        self.btnEditarIngresoDetalle.setObjectName(_fromUtf8("btnEditarIngresoDetalle"))
        self.verticalLayout_15.addWidget(self.btnEditarIngresoDetalle)
        self.btnEliminarIngresoDetalle = QtGui.QPushButton(self.centralwidget)
        self.btnEliminarIngresoDetalle.setObjectName(_fromUtf8("btnEliminarIngresoDetalle"))
        self.verticalLayout_15.addWidget(self.btnEliminarIngresoDetalle)
        spacerItem12 = QtGui.QSpacerItem(20, 180, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_15.addItem(spacerItem12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.tblIngreso, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")),
                               self.ingreso_row_was_clicked)
        QtCore.QObject.connect(self.tblIngresoDetalle, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")),
                               self.ingreso_detalle_row_was_clicked)
        QtCore.QObject.connect(self.btnEliminarIngreso, QtCore.SIGNAL(_fromUtf8("clicked()")),
                               self.eliminar_ingreso)
        QtCore.QObject.connect(self.btnEliminarIngresoDetalle, QtCore.SIGNAL(_fromUtf8("clicked()")),
                               self.eliminar_ingreso_detalle)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self = frm_formato.center(self)
        #  except:

    #            print("Ha ocurrido un error al cargar el formulario")

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.lblListaIngreso.setText(_translate("MainWindow", "Ingresos", None))
        item = self.tblIngreso.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ingreso", None))
        item = self.tblIngreso.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tipo Ingreso", None))
        item = self.tblIngreso.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Paciente", None))
        item = self.tblIngreso.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Fecha Ingreso", None))
        item = self.tblIngreso.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fecha Egreso", None))
        item = self.tblIngreso.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Observaciones", None))
        self.btnNuevoIngreso.setText(_translate("MainWindow", "Nuevo", None))
        self.btnEditarIngreso.setText(_translate("MainWindow", "Editar", None))
        self.btnEliminarIngreso.setText(_translate("MainWindow", "Eliminar", None))
        self.lblPaciente.setText(_translate("MainWindow", "Paciente:", None))
        self.lblIngreso_2.setText(_translate("MainWindow", "Ingreso:", None))
        self.txtIngreso.setHtml(_translate("MainWindow",
                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'Sans Serif\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
                                           "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"><br /></p></body></html>",
                                           None))
        self.lblFechaIngreso.setText(_translate("MainWindow", "Fecha Ingreso:", None))
        self.lblTipoINgreso.setText(_translate("MainWindow", "Tipo de Ingreso:", None))
        self.lblFechaEgreso.setText(_translate("MainWindow", "Fecha Egreso:", None))
        self.lblListaIngresoDetalle.setText(_translate("MainWindow", " Ingresos Detalles", None))
        item = self.tblIngresoDetalle.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "idIngreso", None))
        item = self.tblIngresoDetalle.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Area", None))
        item = self.tblIngresoDetalle.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Centro", None))
        item = self.tblIngresoDetalle.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Personal", None))
        item = self.tblIngresoDetalle.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Fecha Detalle", None))
        item = self.tblIngresoDetalle.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "idAsignacionPersonalCentroArea", None))
        item = self.tblIngresoDetalle.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "idTurno", None))
        item = self.tblIngresoDetalle.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "idAreaCentroEspacio", None))
        self.lblIngreso.setText(_translate("MainWindow", "Ingreso:", None))
        self.lblFechaDetalle.setText(_translate("MainWindow", "Fecha Detalle:", None))
        self.lblArea.setText(_translate("MainWindow", "Area:", None))
        self.lblCentro.setText(_translate("MainWindow", "Centro:", None))
        self.lblDoctor.setText(_translate("MainWindow", "Personal:", None))
        self.btnNuevoIngresoDetalle.setText(_translate("MainWindow", "Nuevo", None))
        self.btnEditarIngresoDetalle.setText(_translate("MainWindow", "Editar", None))
        self.btnEliminarIngresoDetalle.setText(_translate("MainWindow", "Eliminar", None))
        self.tblIngresoDetalle.setColumnHidden(5, True)
        self.tblIngresoDetalle.setColumnHidden(6, True)
        self.tblIngresoDetalle.setColumnHidden(7, True)
        self.refrescar_ingresos()

    def refrescar_ingresos(self):
        try:
            datos = get(entidad="Ingreso")
            self.tblIngreso.setRowCount(len(datos))
            i = 0
            for elemento in datos:
                self.tblIngreso.setItem(i, 0, QtGui.QTableWidgetItem(str(elemento['idIngreso'])))
                self.tblIngreso.setItem(i, 1, QtGui.QTableWidgetItem(elemento['idTipoIngreso']['nombre']))
                self.tblIngreso.setItem(i, 2, QtGui.QTableWidgetItem(
                    elemento['idPaciente']['nombres'] + " " + elemento['idPaciente']['apellidos']))
                if elemento.get('fechaIngreso') != None:
                    self.tblIngreso.setItem(i, 3, QtGui.QTableWidgetItem(elemento['fechaIngreso']))
                if elemento.get('fechaEgreso') != None:
                    self.tblIngreso.setItem(i, 4, QtGui.QTableWidgetItem(elemento['fechaEgreso']))
                if elemento.get('observaciones') != None:
                    self.tblIngreso.setItem(i, 5, QtGui.QTableWidgetItem(elemento['observaciones']))
                i += 1
        except:
            print("Ha ocurrido un error al obtener los ingresos")

    def refrescar_ingresos_detalles(self):
        try:
            row = self.tblIngreso.currentRow()
            IDingreso = str(self.tblIngreso.item(row, 0).text())
            print("Este es el id", IDingreso)
            entidad = "IngresoDetalle" + "/" + IDingreso
            datos = get(entidad)
            self.tblIngresoDetalle.setRowCount(len(datos))
            i = 0
            for elemento in datos:
                self.tblIngresoDetalle.setItem(i, 0, QtGui.QTableWidgetItem(str(elemento['ingreso']['idIngreso'])))
                self.tblIngresoDetalle.setItem(i, 1, QtGui.QTableWidgetItem(
                    elemento['asignacionPersonalCentroAreaEspacio']['asignacionPersonalCentroArea']['idAreaCentro'][
                        'idArea']['nombre']))
                self.tblIngresoDetalle.setItem(i, 2, QtGui.QTableWidgetItem(
                    elemento['asignacionPersonalCentroAreaEspacio']['asignacionPersonalCentroArea']['idAreaCentro'][
                        'idCentro']['nombreCorto']))
                self.tblIngresoDetalle.setItem(i, 3, QtGui.QTableWidgetItem(
                    elemento['asignacionPersonalCentroAreaEspacio']['asignacionPersonalCentroArea']['idPersonal'][
                        'nombres'] + " " +
                    elemento['asignacionPersonalCentroAreaEspacio']['asignacionPersonalCentroArea']['idPersonal'][
                        'apellidos']))
                if elemento.get('fechaDetalle') != None:
                    self.tblIngresoDetalle.setItem(i, 4, QtGui.QTableWidgetItem(elemento['fechaDetalle']))
                self.tblIngresoDetalle.setItem(i, 5, QtGui.QTableWidgetItem(
                    str(elemento['ingresoDetallePK']['idAsignacionPersonalCentroArea'])))
                self.tblIngresoDetalle.setItem(i, 6,
                                               QtGui.QTableWidgetItem(str(elemento['ingresoDetallePK']['idTurno'])))
                self.tblIngresoDetalle.setItem(i, 7, QtGui.QTableWidgetItem(
                    str(elemento['ingresoDetallePK']['idAreaCentroEspacio'])))
                i += 1
        except:
            print("Ha ocurrido un error al obtener los detalles de ese ingreso")

    def ingreso_row_was_clicked(self):
        self.limpiar_ingreso()
        row = self.tblIngreso.currentRow()
        item = self.tblIngreso.item(row, 0)
        self.txtIngreso.setText(item.text())
        item = self.tblIngreso.item(row, 1)
        self.txtTipoIngreso.setText(item.text())
        item = self.tblIngreso.item(row, 2)
        self.txtPaciente.setText(item.text())
        item = self.tblIngreso.item(row, 3)
        if item != None:
            self.txtFechaIngreso.setText(item.text())
        item = self.tblIngreso.item(row, 4)
        if item != None:
            self.txtFechaEgreso.setText(item.text())
        self.refrescar_ingresos_detalles()

    def ingreso_detalle_row_was_clicked(self):
        self.limpiar_ingreso_detalle()
        row = self.tblIngresoDetalle.currentRow()
        if row != -1:
            item = self.tblIngresoDetalle.item(row, 0)
            self.txtIngresoDetalle.setText(item.text())
            item = self.tblIngresoDetalle.item(row, 1)
            self.txtArea.setText(item.text())
            item = self.tblIngresoDetalle.item(row, 2)
            self.txtCentro.setText(item.text())
            item = self.tblIngresoDetalle.item(row, 3)
            self.txtPersonal.setText(item.text())
            item = self.tblIngresoDetalle.item(row, 4)
            if item != None:
                self.txtFechaDetalle.setText(item.text())

    def limpiar_ingreso(self):
        self.txtIngreso.setText("")
        self.txtPaciente.setText("")
        self.txtFechaIngreso.setText("")
        self.txtFechaEgreso.setText("")
        self.txtTipoIngreso.setText("")
        self.tblIngresoDetalle.clearSelection()

    def limpiar_ingreso_detalle(self):
        self.txtIngresoDetalle.setText("")
        self.txtArea.setText("")
        self.txtCentro.setText("")
        self.txtPersonal.setText("")
        self.txtFechaDetalle.setText("")

    def eliminar_ingreso(self):
        row = self.tblIngreso.currentRow()
        item = self.tblIngreso.item(row, 0).text()
        entidad = "Ingreso" + "/" + str(item)
        print("Ingreso a eliminar: ", "Ingreso" + "/" + str(item))
        # recurso.delete(entidad)
        delete(entidad)
        self.refrescar_ingresos()
        self.refrescar_ingresos_detalles()

    def eliminar_ingreso_detalle(self):
        row = self.tblIngreso.currentRow()
        idIngreso = str(self.tblIngreso.item(row, 0).text())
        row = self.tblIngresoDetalle.currentRow()
        idACE = str(self.tblIngresoDetalle.item(row, 7).text())
        idAPCA = str(self.tblIngresoDetalle.item(row, 5).text())
        idTurno = str(self.tblIngresoDetalle.item(row, 6).text())
        entidad = "IngresoDetalle/" + idIngreso + "/" + idAPCA + "/" + idACE + "/" + idTurno
        delete(entidad)
        self.refrescar_ingresos_detalles()


def get(entidad):
    try:
        response = recurso.get(entidad)
        data = jsonFormato.deserializar(response)
        return data
    except:
        print("Ha ocurrido un error")


def delete(entidad):
    try:
        recurso.delete(entidad)
    except:
        print("Ha ocurrido un error")
